{% set name = "tableschema-sql" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31a2e04fb8ddcc08a8ba0fe904db16c6ab614394f2db88ee1458aa252423c7c0

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six >=1.9
    - sqlalchemy >=1.0
    - pybloom_live >=2.2
    - tabulator >=1.0.0a5
    - tableschema >=1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - tableschema_sql

about:
  home: http://github.com/frictionlessdata/tableschema-sql-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Generate and load SQL tables based on Table Schema descriptors.'

extra:
  recipe-maintainers:
    - roll
